elemento = input('digite algo:')
print(elemento.isalnum())
print(elemento.isalpha())
print(elemento.isascii())
print(elemento.isdigit())
print(elemento.islower())
print(elemento.isdecimal())
print(elemento.isidentifier())
print(elemento.isnumeric())
print(elemento.isprintable())
print(elemento.isspace())
print(elemento.istitle())
print(elemento.isupper())